name: leakage_detection
description: leakage detection package

version: 0.0.1

environment:
  sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # other dependencies

dev_dependencies:
  # dev dependencies

publish_to: 'none'

author: Bagirishya Rwema dDominique
homepage: https://github.com/rwema3/Packages-Development\Leak Detection

